// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjArL08Moptva0o5YDIRWACxDo74hCB18',
    appId: '1:1007515095448:web:6ee9d051ee9588ada21bed',
    messagingSenderId: '1007515095448',
    projectId: 'dhqhospital-bf647',
    authDomain: 'dhqhospital-bf647.firebaseapp.com',
    databaseURL: 'https://dhqhospital-bf647-default-rtdb.firebaseio.com',
    storageBucket: 'dhqhospital-bf647.firebasestorage.app',
    measurementId: 'G-NTLKMM8XF4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhBRv6PmCaxobV6259ZcHgKD14AH90xZI',
    appId: '1:1007515095448:android:c5d6cfbae553afa9a21bed',
    messagingSenderId: '1007515095448',
    projectId: 'dhqhospital-bf647',
    databaseURL: 'https://dhqhospital-bf647-default-rtdb.firebaseio.com',
    storageBucket: 'dhqhospital-bf647.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjArL08Moptva0o5YDIRWACxDo74hCB18',
    appId: '1:1007515095448:web:864180f4f750d2eca21bed',
    messagingSenderId: '1007515095448',
    projectId: 'dhqhospital-bf647',
    authDomain: 'dhqhospital-bf647.firebaseapp.com',
    databaseURL: 'https://dhqhospital-bf647-default-rtdb.firebaseio.com',
    storageBucket: 'dhqhospital-bf647.firebasestorage.app',
    measurementId: 'G-G5C915GJRT',
  );
}
